### ISSUE TITLE
(fenix) `MainDispatcherLoader.<clinit>` unexpectedly takes 266ms on COLD start up

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#20824]
See https://github.com/mozilla-mobile/focus-android/issues/5102 for details and analysis.

**Comment by mcomella** [comment]
I tried to downgrade to AGP v4.2.0, as suggested in the other bug, but I get a compilation error, similar to the other bug:
```
error: this version (1.0.0) of the Compose Compiler requires Kotlin version 1.5.10 but you appear to be using Kotlin version 1.4.31 which is not known to be compatible.  Please fix your configuration (or `suppressKotlinVersionCompatibilityCheck` but don't say I didn't warn you!).

> Task :app:compileNightlyKotlin FAILED
```

**Comment by mcomella** [comment]
This regression is from 08afc2ed5a2544fe7f738510830389c52bc077f2. As far as I can tell, it's not in the release channel (v91.1.0):
```
$ git log 08afc2ed5a2544fe7f738510830389c52bc077f2..v91.1.0 --ancestry-path
$
```

But it's in v92.0.0-beta2:
```
$ git log 08afc2ed5a2544fe7f738510830389c52bc077f2..v92.0.0-beta.2 --ancestry-path
commit b54a8897441f52f5a588c393d394b2f5f8ad952a (HEAD, tag: v92.0.0-beta.2)
...
```

I also double checked by checking out the revisions locally and verifying the version number in `Dependencies.kt`.

Next merge to release is in 24 days so we should address this by then.

**Comment by mcomella** [comment]
See https://github.com/mozilla-mobile/focus-android/pull/5122 for the proposed fix in Focus.

**Comment by mcomella** [comment]
PR: https://github.com/mozilla-mobile/fenix/pull/20844

**Comment by mcomella** [comment]
Once my PR lands, I'm also going to backport to v92 beta.

**Comment by mcomella** [comment]
Backport PR: https://github.com/mozilla-mobile/fenix/pull/20908

**Comment by mcomella** [comment]
PR landed & backported: closing.
