### ISSUE TITLE
[Bug] Lint Error aborts build on Ubuntu 18.04

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/fenix#3281]
## Steps to reproduce
From #2736, the mystery lint crash seems to be the following error.  It was shown when heap space was increased.

When executing ```RUN ./gradlew -PversionName=0.0 --no-daemon assemble test lint```

```
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...

  Errors found:

  /opt/fenix/app/src/main/res/drawable/ic_report_issues.xml:15: Error: Use -0.7 instead of -.7 to avoid crashes on some devices [InvalidVectorPath]
          android:pathData="M12 2C7.7 2 5 4.8 5 9c0 3 2 5 3 6v4.5c0 1.8 2.4 2.5 4 2.5s4-.7 4-2.5V15c1-1 3-3 3-6 0-4.2-2.7-7-7-7zm0 2C9.9 4 7 5.4 7 9c0 2 1.7 3.9 2.5 4.5 0.3 0.2 0.5 0.6 0.5 1v5l2 0.5 2-0.5v-5c0-0.4 0.2-0.8 0.5-1C15.3 12.9 17 11 17 9c0-3.6-2.9-5-5-5z" />
                                                                                       ~~~
  /opt/fenix/app/src/main/java/org/mozilla/fenix/onboarding/OnboardingRadioButton.kt:13: Error: This custom view should extend android.support.v7.widget.AppCompatRadioButton instead [AppCompatCustomView]
  class OnboardingRadioButton : RadioButton {
```

Since ```lintDebug``` makes builds pass, perhaps we could set the build command in Dockerfile to 
```RUN ./gradlew -PversionName=0.0 --no-daemon assemble test lintDebug``` ?
