### ISSUE TITLE
FNX-4569 ⁃ [Bug]Reader mode not working on Beta 5.1.0-beta.1

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#10796]
## Steps to reproduce
1. Navigate to https://en.m.wikipedia.org/wiki/Main_Page
1. Tap and open the  ⋮ Main menu
1. Enable Reader Mode

### Expected behavior
The website should be reloaded in Reader mode

### Actual behavior
Nothing happens

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version: Beta 5.1.0-beta.1

### Notes
:heavy_check_mark: Works on the latest **`Nightly 200520 from 5/20`**
❗ Checked other websites, but still Reader mode doesn't work

► Video
![20200520-143241](https://user-images.githubusercontent.com/51314259/82442006-86341e80-9aa7-11ea-9aed-8f79c0fd7a75.gif)

**Comment by csadilek** [comment]
The cause of this is that latest reader mode is using `Promise.any` which is not supported yet on beta :(. This needs a workaround in A-C.

```
TypeError: "Promise.any is not a function"
    showAsync moz-extension://386529cf-6dd2-48ea-9e76-b00dcbd20437/readerview.js:340
    connectNativePort moz-extension://386529cf-6dd2-48ea-9e76-b00dcbd20437/readerview.js:350
readerview.js:343:21
```

**Comment by csadilek** [comment]
Fix landed in A-C and will be available in next beta build.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Beta 5.1.0-beta.2 build, and on 5/27 Nightly build with Samsung Galaxy Note 8 (Android 9), Samsung Galaxy Tab A6 (Android 5.1.1), Google Pixel (Android 10), and Sony Xperia Z5 Premium (Android 7.1.1).
